# *Broadcasting*

Hemos visto como la vectorización es la estrategia que permite eliminar
bucles lentos. Se denomina *broadcasting* en este contexto a las reglas
que permiten aplicar la vectorización a *arrays de diferente tamaño*.

In [1]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([4, 4, 4])
a + b

array([4, 5, 6])

Supongamos ahora que queremos aplicar la suma con un escalar

In [2]:
a + 4

array([4, 5, 6])

El resultado es equivalente a extender o difundir (*bradcast*) el escalar
al tamaño completo del array. Es importante recalcar que esta extensión
no se realiza en memoria (no se crea un array nuevo) pero es un modelo para
entender lo que sucede.

Veamos que sucede si extendemos la operación a un caso bidimensional.

In [3]:
c = np.ones((3, 3))
a + c

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

En este caso, el array `a` se ha extendido